import { CreateInvoiceTool } from "./create-invoice.tool.js";
import { RegisterTool } from "../helpers/register-tool.js";
import { ReadInvoiceTool } from "./read-invoice.tool.js";
import { SearchInvoicesTool } from "./search-invoices.tool.js";
import { UpdateInvoiceTool } from "./update-invoice.tool.js";
import { GetInvoicePdfTool } from "./get-invoice-pdf.tool.js";
import { CreateAccountTool } from "./create-account.tool.js";
import { UpdateAccountTool } from "./update-account.tool.js";
import { SearchAccountsTool } from "./search-accounts.tool.js";
import { ReadItemTool } from "./read-item.tool.js";
import { SearchItemsTool } from "./search-items.tool.js";
import { CreateItemTool } from "./create-item.tool.js";
import { UpdateItemTool } from "./update-item.tool.js";
import { DeleteItemTool } from "./delete-item.tool.js";
import { GetAccountTool } from "./get-account.tool.js";
import { DeleteInvoiceTool } from "./delete-invoice.tool.js";
import { CreateCustomerTool } from "./create-customer.tool.js";
import { GetCustomerTool } from "./get-customer.tool.js";
import { UpdateCustomerTool } from "./update-customer.tool.js";
import { DeleteCustomerTool } from "./delete-customer.tool.js";
import { CreateEstimateTool } from "./create-estimate.tool.js";
import { GetEstimateTool } from "./get-estimate.tool.js";
import { UpdateEstimateTool } from "./update-estimate.tool.js";
import { DeleteEstimateTool } from "./delete-estimate.tool.js";
import { SearchCustomersTool } from "./search-customers.tool.js";
import { SearchEstimatesTool } from "./search-estimates.tool.js";
import { CreateBillTool } from "./create-bill.tool.js";
import { UpdateBillTool } from "./update-bill.tool.js";
import { DeleteBillTool } from "./delete-bill.tool.js";
import { GetBillTool } from "./get-bill.tool.js";
import { CreateVendorTool } from "./create-vendor.tool.js";
import { UpdateVendorTool } from "./update-vendor.tool.js";
import { DeleteVendorTool } from "./delete-vendor.tool.js";
import { GetVendorTool } from "./get-vendor.tool.js";
import { SearchBillsTool } from "./search-bills.tool.js";
import { SearchVendorsTool } from "./search-vendors.tool.js";
import { CreateEmployeeTool } from "./create-employee.tool.js";
import { GetEmployeeTool } from "./get-employee.tool.js";
import { UpdateEmployeeTool } from "./update-employee.tool.js";
import { SearchEmployeesTool } from "./search-employees.tool.js";
import { DeleteEmployeeTool } from "./delete-employee.tool.js";
import { CreateJournalEntryTool } from "./create-journal-entry.tool.js";
import { GetJournalEntryTool } from "./get-journal-entry.tool.js";
import { UpdateJournalEntryTool } from "./update-journal-entry.tool.js";
import { DeleteJournalEntryTool } from "./delete-journal-entry.tool.js";
import { SearchJournalEntriesTool } from "./search-journal-entries.tool.js";
import { CreateBillPaymentTool } from "./create-bill-payment.tool.js";
import { GetBillPaymentTool } from "./get-bill-payment.tool.js";
import { UpdateBillPaymentTool } from "./update-bill-payment.tool.js";
import { DeleteBillPaymentTool } from "./delete-bill-payment.tool.js";
import { SearchBillPaymentsTool } from "./search-bill-payments.tool.js";
import { CreatePurchaseTool } from "./create-purchase.tool.js";
import { GetPurchaseTool } from "./get-purchase.tool.js";
import { UpdatePurchaseTool } from "./update-purchase.tool.js";
import { DeletePurchaseTool } from "./delete-purchase.tool.js";
import { SearchPurchasesTool } from "./search-purchases.tool.js";
import { CreatePaymentTool } from "./create-payment.tool.js";
import { GetPaymentTool } from "./get-payment.tool.js";
import { UpdatePaymentTool } from "./update-payment.tool.js";
import { DeletePaymentTool } from "./delete-payment.tool.js";
import { SearchPaymentsTool } from "./search-payments.tool.js";
import { CreateSalesReceiptTool } from "./create-sales-receipt.tool.js";
import { GetSalesReceiptTool } from "./get-sales-receipt.tool.js";
import { UpdateSalesReceiptTool } from "./update-sales-receipt.tool.js";
import { DeleteSalesReceiptTool } from "./delete-sales-receipt.tool.js";
import { SearchSalesReceiptsTool } from "./search-sales-receipts.tool.js";
import { CreateCreditMemoTool } from "./create-credit-memo.tool.js";
import { GetCreditMemoTool } from "./get-credit-memo.tool.js";
import { UpdateCreditMemoTool } from "./update-credit-memo.tool.js";
import { DeleteCreditMemoTool } from "./delete-credit-memo.tool.js";
import { SearchCreditMemosTool } from "./search-credit-memos.tool.js";
import { CreateRefundReceiptTool } from "./create-refund-receipt.tool.js";
import { GetRefundReceiptTool } from "./get-refund-receipt.tool.js";
import { UpdateRefundReceiptTool } from "./update-refund-receipt.tool.js";
import { DeleteRefundReceiptTool } from "./delete-refund-receipt.tool.js";
import { SearchRefundReceiptsTool } from "./search-refund-receipts.tool.js";
import { CreatePurchaseOrderTool } from "./create-purchase-order.tool.js";
import { GetPurchaseOrderTool } from "./get-purchase-order.tool.js";
import { UpdatePurchaseOrderTool } from "./update-purchase-order.tool.js";
import { DeletePurchaseOrderTool } from "./delete-purchase-order.tool.js";
import { SearchPurchaseOrdersTool } from "./search-purchase-orders.tool.js";
import { CreateVendorCreditTool } from "./create-vendor-credit.tool.js";
import { GetVendorCreditTool } from "./get-vendor-credit.tool.js";
import { UpdateVendorCreditTool } from "./update-vendor-credit.tool.js";
import { DeleteVendorCreditTool } from "./delete-vendor-credit.tool.js";
import { SearchVendorCreditsTool } from "./search-vendor-credits.tool.js";
import { CreateDepositTool } from "./create-deposit.tool.js";
import { GetDepositTool } from "./get-deposit.tool.js";
import { UpdateDepositTool } from "./update-deposit.tool.js";
import { DeleteDepositTool } from "./delete-deposit.tool.js";
import { SearchDepositsTool } from "./search-deposits.tool.js";
import { CreateTransferTool } from "./create-transfer.tool.js";
import { GetTransferTool } from "./get-transfer.tool.js";
import { UpdateTransferTool } from "./update-transfer.tool.js";
import { DeleteTransferTool } from "./delete-transfer.tool.js";
import { SearchTransfersTool } from "./search-transfers.tool.js";
import { CreateTimeActivityTool } from "./create-time-activity.tool.js";
import { GetTimeActivityTool } from "./get-time-activity.tool.js";
import { UpdateTimeActivityTool } from "./update-time-activity.tool.js";
import { DeleteTimeActivityTool } from "./delete-time-activity.tool.js";
import { SearchTimeActivitiesTool } from "./search-time-activities.tool.js";
import { CreateClassTool } from "./create-class.tool.js";
import { GetClassTool } from "./get-class.tool.js";
import { UpdateClassTool } from "./update-class.tool.js";
import { SearchClassesTool } from "./search-classes.tool.js";
import { CreateDepartmentTool } from "./create-department.tool.js";
import { GetDepartmentTool } from "./get-department.tool.js";
import { UpdateDepartmentTool } from "./update-department.tool.js";
import { SearchDepartmentsTool } from "./search-departments.tool.js";
import { CreateTermTool } from "./create-term.tool.js";
import { GetTermTool } from "./get-term.tool.js";
import { UpdateTermTool } from "./update-term.tool.js";
import { SearchTermsTool } from "./search-terms.tool.js";
import { CreatePaymentMethodTool } from "./create-payment-method.tool.js";
import { GetPaymentMethodTool } from "./get-payment-method.tool.js";
import { UpdatePaymentMethodTool } from "./update-payment-method.tool.js";
import { SearchPaymentMethodsTool } from "./search-payment-methods.tool.js";
import { SearchBudgetsTool } from "./search-budgets.tool.js";
import { GetTaxCodeTool } from "./get-tax-code.tool.js";
import { SearchTaxCodesTool } from "./search-tax-codes.tool.js";
import { GetTaxRateTool } from "./get-tax-rate.tool.js";
import { SearchTaxRatesTool } from "./search-tax-rates.tool.js";
import { GetTaxAgencyTool } from "./get-tax-agency.tool.js";
import { SearchTaxAgenciesTool } from "./search-tax-agencies.tool.js";
import { GetCompanyInfoTool } from "./get-company-info.tool.js";
import { UpdateCompanyInfoTool } from "./update-company-info.tool.js";
import { GetPreferencesTool } from "./get-preferences.tool.js";
import { CreateAttachableTool } from "./create-attachable.tool.js";
import { GetAttachableTool } from "./get-attachable.tool.js";
import { UpdateAttachableTool } from "./update-attachable.tool.js";
import { DeleteAttachableTool } from "./delete-attachable.tool.js";
import { SearchAttachablesTool } from "./search-attachables.tool.js";
import { GetBalanceSheetTool } from "./get-balance-sheet.tool.js";
import { GetProfitAndLossTool } from "./get-profit-and-loss.tool.js";
import { GetCashFlowTool } from "./get-cash-flow.tool.js";
import { GetTrialBalanceTool } from "./get-trial-balance.tool.js";
import { GetGeneralLedgerTool } from "./get-general-ledger.tool.js";
import { GetCustomerSalesTool } from "./get-customer-sales.tool.js";
import { GetAgedReceivablesTool } from "./get-aged-receivables.tool.js";
import { GetCustomerBalanceTool } from "./get-customer-balance.tool.js";
import { GetAgedPayablesTool } from "./get-aged-payables.tool.js";
import { GetVendorExpensesTool } from "./get-vendor-expenses.tool.js";
import { GetVendorBalanceTool } from "./get-vendor-balance.tool.js";
import { GetTransactionListTool } from "./get-transaction-list.tool.js";
import { DeleteAccountTool } from "./delete-account.tool.js";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";

/** Registers every QuickBooks tool on the given server (shared by the stdio and HTTP entry points). */
export function registerAllTools(server: McpServer): void {
  RegisterTool(server, CreateCustomerTool);
  RegisterTool(server, GetCustomerTool);
  RegisterTool(server, UpdateCustomerTool);
  RegisterTool(server, DeleteCustomerTool);
  RegisterTool(server, SearchCustomersTool);
  RegisterTool(server, CreateEstimateTool);
  RegisterTool(server, GetEstimateTool);
  RegisterTool(server, UpdateEstimateTool);
  RegisterTool(server, DeleteEstimateTool);
  RegisterTool(server, SearchEstimatesTool);
  RegisterTool(server, CreateBillTool);
  RegisterTool(server, UpdateBillTool);
  RegisterTool(server, DeleteBillTool);
  RegisterTool(server, GetBillTool);
  RegisterTool(server, SearchBillsTool);
  RegisterTool(server, ReadInvoiceTool);
  RegisterTool(server, SearchInvoicesTool);
  RegisterTool(server, CreateInvoiceTool);
  RegisterTool(server, UpdateInvoiceTool);
  RegisterTool(server, DeleteInvoiceTool);
  RegisterTool(server, GetInvoicePdfTool);
  RegisterTool(server, CreateAccountTool);
  RegisterTool(server, GetAccountTool);
  RegisterTool(server, UpdateAccountTool);
  RegisterTool(server, DeleteAccountTool);
  RegisterTool(server, SearchAccountsTool);
  RegisterTool(server, ReadItemTool);
  RegisterTool(server, SearchItemsTool);
  RegisterTool(server, CreateItemTool);
  RegisterTool(server, UpdateItemTool);
  RegisterTool(server, DeleteItemTool);
  RegisterTool(server, CreateVendorTool);
  RegisterTool(server, UpdateVendorTool);
  RegisterTool(server, DeleteVendorTool);
  RegisterTool(server, GetVendorTool);
  RegisterTool(server, SearchVendorsTool);
  RegisterTool(server, CreateEmployeeTool);
  RegisterTool(server, GetEmployeeTool);
  RegisterTool(server, UpdateEmployeeTool);
  RegisterTool(server, DeleteEmployeeTool);
  RegisterTool(server, SearchEmployeesTool);
  RegisterTool(server, CreateJournalEntryTool);
  RegisterTool(server, GetJournalEntryTool);
  RegisterTool(server, UpdateJournalEntryTool);
  RegisterTool(server, DeleteJournalEntryTool);
  RegisterTool(server, SearchJournalEntriesTool);
  RegisterTool(server, CreateBillPaymentTool);
  RegisterTool(server, GetBillPaymentTool);
  RegisterTool(server, UpdateBillPaymentTool);
  RegisterTool(server, DeleteBillPaymentTool);
  RegisterTool(server, SearchBillPaymentsTool);
  RegisterTool(server, CreatePurchaseTool);
  RegisterTool(server, GetPurchaseTool);
  RegisterTool(server, UpdatePurchaseTool);
  RegisterTool(server, DeletePurchaseTool);
  RegisterTool(server, SearchPurchasesTool);
  RegisterTool(server, CreatePaymentTool);
  RegisterTool(server, GetPaymentTool);
  RegisterTool(server, UpdatePaymentTool);
  RegisterTool(server, DeletePaymentTool);
  RegisterTool(server, SearchPaymentsTool);
  RegisterTool(server, CreateSalesReceiptTool);
  RegisterTool(server, GetSalesReceiptTool);
  RegisterTool(server, UpdateSalesReceiptTool);
  RegisterTool(server, DeleteSalesReceiptTool);
  RegisterTool(server, SearchSalesReceiptsTool);
  RegisterTool(server, CreateCreditMemoTool);
  RegisterTool(server, GetCreditMemoTool);
  RegisterTool(server, UpdateCreditMemoTool);
  RegisterTool(server, DeleteCreditMemoTool);
  RegisterTool(server, SearchCreditMemosTool);
  RegisterTool(server, CreateRefundReceiptTool);
  RegisterTool(server, GetRefundReceiptTool);
  RegisterTool(server, UpdateRefundReceiptTool);
  RegisterTool(server, DeleteRefundReceiptTool);
  RegisterTool(server, SearchRefundReceiptsTool);
  RegisterTool(server, CreatePurchaseOrderTool);
  RegisterTool(server, GetPurchaseOrderTool);
  RegisterTool(server, UpdatePurchaseOrderTool);
  RegisterTool(server, DeletePurchaseOrderTool);
  RegisterTool(server, SearchPurchaseOrdersTool);
  RegisterTool(server, CreateVendorCreditTool);
  RegisterTool(server, GetVendorCreditTool);
  RegisterTool(server, UpdateVendorCreditTool);
  RegisterTool(server, DeleteVendorCreditTool);
  RegisterTool(server, SearchVendorCreditsTool);
  RegisterTool(server, CreateDepositTool);
  RegisterTool(server, GetDepositTool);
  RegisterTool(server, UpdateDepositTool);
  RegisterTool(server, DeleteDepositTool);
  RegisterTool(server, SearchDepositsTool);
  RegisterTool(server, CreateTransferTool);
  RegisterTool(server, GetTransferTool);
  RegisterTool(server, UpdateTransferTool);
  RegisterTool(server, DeleteTransferTool);
  RegisterTool(server, SearchTransfersTool);
  RegisterTool(server, CreateTimeActivityTool);
  RegisterTool(server, GetTimeActivityTool);
  RegisterTool(server, UpdateTimeActivityTool);
  RegisterTool(server, DeleteTimeActivityTool);
  RegisterTool(server, SearchTimeActivitiesTool);
  RegisterTool(server, CreateClassTool);
  RegisterTool(server, GetClassTool);
  RegisterTool(server, UpdateClassTool);
  RegisterTool(server, SearchClassesTool);
  RegisterTool(server, CreateDepartmentTool);
  RegisterTool(server, GetDepartmentTool);
  RegisterTool(server, UpdateDepartmentTool);
  RegisterTool(server, SearchDepartmentsTool);
  RegisterTool(server, CreateTermTool);
  RegisterTool(server, GetTermTool);
  RegisterTool(server, UpdateTermTool);
  RegisterTool(server, SearchTermsTool);
  RegisterTool(server, CreatePaymentMethodTool);
  RegisterTool(server, GetPaymentMethodTool);
  RegisterTool(server, UpdatePaymentMethodTool);
  RegisterTool(server, SearchPaymentMethodsTool);
  RegisterTool(server, SearchBudgetsTool);
  RegisterTool(server, GetTaxCodeTool);
  RegisterTool(server, SearchTaxCodesTool);
  RegisterTool(server, GetTaxRateTool);
  RegisterTool(server, SearchTaxRatesTool);
  RegisterTool(server, GetTaxAgencyTool);
  RegisterTool(server, SearchTaxAgenciesTool);
  RegisterTool(server, GetCompanyInfoTool);
  RegisterTool(server, UpdateCompanyInfoTool);
  RegisterTool(server, GetPreferencesTool);
  RegisterTool(server, CreateAttachableTool);
  RegisterTool(server, GetAttachableTool);
  RegisterTool(server, UpdateAttachableTool);
  RegisterTool(server, DeleteAttachableTool);
  RegisterTool(server, SearchAttachablesTool);
  RegisterTool(server, GetBalanceSheetTool);
  RegisterTool(server, GetProfitAndLossTool);
  RegisterTool(server, GetCashFlowTool);
  RegisterTool(server, GetTrialBalanceTool);
  RegisterTool(server, GetGeneralLedgerTool);
  RegisterTool(server, GetTransactionListTool);
  RegisterTool(server, GetCustomerSalesTool);
  RegisterTool(server, GetAgedReceivablesTool);
  RegisterTool(server, GetCustomerBalanceTool);
  RegisterTool(server, GetAgedPayablesTool);
  RegisterTool(server, GetVendorExpensesTool);
  RegisterTool(server, GetVendorBalanceTool);
}
